In [2]:
import numpy as np

In [4]:
x=np.array([[1,1,2],[2,2,3]])

In [5]:
x.ravel()

array([1, 1, 2, 2, 2, 3])

In [9]:
p,q=np.unique(x.ravel(),return_inverse=True)

In [10]:
q

array([0, 0, 1, 1, 1, 2], dtype=int64)

In [11]:
np.interp()

array([1, 2, 3])

In [ ]:
np.interp()